# Generated by Django 4.2.7 on 2025-12-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='규칙 이름 (예: 성별 숫자→텍스트)', max_length=200)),
                ('source_variable', models.CharField(help_text='원본 변수명', max_length=100)),
                ('target_variable', models.CharField(help_text='새 변수명', max_length=100)),
                ('rules', models.JSONField(help_text='변환 규칙들 (JSON)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recode_rules', to='surveys.surveydata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recode Rule',
                'verbose_name_plural': 'Recode Rules',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'dataset', 'target_variable')},
            },
        ),
    ]
